name: Angular Pipeline File

on:
  push:
    branches: [ $default-branch ]

jobs:
  pipeline:
    uses: soo-doh-kohd/pipeline/.github/workflows/angular-pipeline.yml@main
    with:
      environment: 'dev' # The environment you are deploying to.
      project-name: '' # The name of your project.
      node-version: '14.x' # The version of Node the application uses.
